sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build app
  - docker-compose build app-tests

script:
  - >
    docker-compose run
    --rm
    -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
    app-tests-with-report

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack:
    secure: sImUwXx2qKwSSTFkzgV6ExOLpcubSYFyTBQB+tokx2YNXmpTjadghhgiO/xa3gFZ573ZJGJgqkRQmhDrPgFykvmMPXZmpgwDk+Z5z3jKe6Zg0EJmzba1bI8WOeLZgFwyFIE3ynbIyG4Lh8uWotgx6MrznmwBbAHKk8/wZZqHzS4ZbLhq2uvvPhjjsy6YiyuDcMe1LC29uybxhKeZ4DsUyk1+Dhx1cChLzxmfkF5w86KKqYeryTZKOMcsgvTOyAQiPNJh1kRbqmctTJSOdqsNK7ixyz/Q6ZsMnu+nMRbLDgHPyaMh13L9smP5Skq0w+CS/DyGGpu5O7slY8Zg6+zzMTAzh723y73ZjcypUnpaEhuxuiKQO3ATf2eVxFsGf05bVvuSscd1OQRRewhSpWq5E7jAPpm3GmHGi/N8dJ1qGxCYn3jBmB6vc3YgbKwVrFkF00oKYkV72ngsKfuVvYAZeF2U4rlEFZbT2GCXm2fTnZKnRtVr3WQLqsoWiBBBvHeBg3nLmC03fRmFbuUmk1WHINcFNcUoIR+H0CmmMOGtUXWR8iPLfWPp7lQh0yxO88C2VkA+PnL58Bqq9k+ZFNTN4uYFc3XuJ8Yn+6OGY49Lq1QGfOKP8YhRKUN2PvwUhS5AiiYhhG005KpBOOF9dZc4QkuZhHdpHGMRONBSYOap9mI=
