version: "2"

services:

  app:
    build: .
    image: keboola/fakturoid-writer
    tty: true
    command: bash
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  app-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: sh -c './tests.sh'

  app-tests-with-report:
    build:
      context: .
      dockerfile: Dockerfile-tests
    links:
      - dynamodb
    command: >
             sh -c '
             && ./tests.sh
             && ./vendor/bin/test-reporter
             '
    volumes:
      - ./.git:/code/.git
