version: "2"

services:

  app:
    build: .
    image: keboola/fakturoid-writer
    tty: true
    command: bash
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  app-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: sh -c './tests.sh'

  app-tests-with-report:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: >-
             sh -c '
             curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
             && chmod +x ./cc-test-reporter
             && ./cc-test-reporter before-build
             && ./tests.sh
             && ./cc-test-reporter after-build
             '
    volumes:
      - ./.git:/code/.git
